### ISSUE TITLE
Add a world class developer friendly readme for this project

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#1]
The readme for any project is as good as the project itself. I was looking through different Readme files and I tried compiling something as well. The one I came up with is something like this:

**Table of Contents**

- Name Inspirations
- Demo
- Use Cases
- Working
- Development
   - System Requirements
   - Installation
   - Testing
- Contributing
- Thanks

Currently, the readme this project has, is created by the Create React App boilerplate. I have seen some good ideas coming up here: [matiassingers/awesome-readme: A curated list of awesome READMEs](https://github.com/matiassingers/awesome-readme), where we can get inspiration from.

We need something that is not cluttered as well as looks professional and decent. 😊

**Comment by habeeba-naaz** [comment]
I am interested to work

**Comment by praveenscience** [comment]
Liaise with @AnjaliSharma1234 with the above ideas. Feel free to add your comments too! 😊

**Comment by habeeba-naaz** [comment]
Sure... thank you @praveenscience

**Comment by AnjaliSharma1234** [comment]
Hey, @habeeba-naaz your inputs will be helpful but I don't think two people can work on the same issue simultaneously. If you have any specific idea that can be implemented in the Readme, do comment. otherwise, feel free to reach out to @praveenscience and create new issues on which we all can work!

**Comment by praveenscience** [comment]
@habeeba-naaz Looks like only one person can do the Pull Request and only they'll get the points. We can leave this to @AnjaliSharma1234 for now and if you have new ideas to be implemented on the document, let's create another issue to address them and you own it. How does that sound?

**Comment by habeeba-naaz** [comment]
Okay...I’ll work on another issue

**Comment by imabp** [comment]
@praveenscience  is there any deadline for the current assignee?

**Comment by praveenscience** [comment]
@imabp I am currently in talks with @AnjaliSharma1234 to finish this off, she's on track. Deadline March 31st. 😊
