### ISSUE TITLE
Use useState Hooks to maintain hooks for those class components using states

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#10]
Find all the classful components and convert them into stateless functional components. If there are any states in it, let's use `useState` hooks.

**Comment by dibakar95** [comment]
Hi, I'd like to do this.

**Comment by praveenscience** [comment]
This fix by @dibakar95 completely broke the application.

**Comment by dibakar95** [comment]
okay. I'll fix this. @praveenscience

**Comment by praveenscience** [comment]
Please kindly create a new PR ASAP.

**Comment by dibakar95** [comment]
Sure. Working on it.

**Comment by praveenscience** [comment]
Thanks bro! 😊 Give me a quick shout if you have questions.

**Comment by dibakar95** [comment]
@praveenscience Sir made a PR. Can you give it a check
