### ISSUE TITLE
Implement the "About Us" section

### ISSUE THREAD

**Issue by mayonk-kumar-git** [CatsInTech/Rezume#101]
### Is your feature request related to a problem? Please describe.

Currently, the "About Us" button in the navbar is just a dummy button and does not route us to any page. 

### Describe the solution you'd like.

I would like to make the "About us" button functional.

I am thinking of : 
- Designing and Implementing the About Us page
- Adding  onClick to the About Us button so that it routes us to the About Us page
- (optional) Styling the About Us button to fit in more with our NavBar design 
- (optional) Making the Rezume logo clickable and routing it to a "Home Page"

### Describe alternatives you've considered.

If we are not interested in implementing an "About Us" then we might as well remove the button from the navbar, because it is not serving any purpose.

**Comment by Arijit018** [comment]
Hey!! I am a GSSOC22 Participant. I want to work on this issue. Can you please assign me ??

**Comment by praveenscience** [comment]
@Arijit018 Currently @mayonk-kumar-git is working on the same.

**Comment by Arijit018** [comment]
@praveenscience  Yes , It's fine . I want to collaborate with @mayonk-kumar-git

**Comment by mayonk-kumar-git** [comment]
@praveenscience Yeah, I am up for it!!
Share the repository

**Comment by praveenscience** [comment]
@mayonk-kumar-git Waiting to get the sign off from GSSoC 22 team! 😊
