### ISSUE TITLE
Title: Design logo and favicon for the website

### ISSUE THREAD

**Issue by Abhilasha-Jairath** [CatsInTech/Rezume#103]
### Is your feature request related to a problem? Please describe.

The website is very simple and lacks elements that can attract users. Logo attracts peoples interest and favicon resonates with searches.

### Describe the solution you'd like.

I would like to design the logo and favicon and make website look attractive with respect of users.

### Describe alternatives you've considered.

If not interested then ill make the nav section interesting so that ppl scroll the ret of the site.

**Comment by praveenscience** [comment]
Really a thoughtful idea @Abhilasha-Jairath, please go ahead and start working on this.

**Comment by Keyurchaniyara** [comment]
Hello @Abhilasha-Jairath 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.

ThankYou:)

**Comment by prachi1211** [comment]
Hello
I am a Gssoc'22 Contributor. Kindly assign me this task.
Thank You.

**Comment by YatreeLadani** [comment]
I'm an GSSOc'22 Contributor, please Assign me this task.

**Comment by Abhilasha-Jairath** [comment]
> Hello
> 
> I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.
> 
> ThankYou:)

Its been assigned. Kindly try some other issue.

**Comment by Abhilasha-Jairath** [comment]
Its been assigned. Kindly try some other issue.

**Comment by praveenscience** [comment]
@Abhilasha-Jairath Any update on this? 😊  Eager to see the design. Thanks for responding though.

**Comment by Abhilasha-Jairath** [comment]
> @Abhilasha-Jairath Any update on this? 😊 Eager to see the design. Thanks for responding though.

Working on it sir !! Will update the designs asap

**Comment by praveenscience** [comment]
@Abhilasha-Jairath Excellent, waiting...

**Comment by praveenscience** [comment]
Ma'am TBH, I am partially colour blind and I trust your decisions on the colours. So please carry on and show some magic! 😁

**Comment by Abhilasha-Jairath** [comment]
Please chk the[ link](https://www.canva.com/design/DAE6-BfhRRI/iSEdHzAoArem4rlxsVFYrQ/view?utm_content=DAE6-BfhRRI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) and lemme know your opinion and changes you need

**Comment by praveenscience** [comment]
Cool, I love the second one... We should also combine this with #6. May I move you there?
