### ISSUE TITLE
Landing Page for the website

### ISSUE THREAD

**Issue by anushkachauhxn** [CatsInTech/Rezume#104]
### Is your feature request related to a problem? Please describe.

I realized that there is no landing page for the website. It might be frustrating for a user who doesn't know the functionalities we provide beforehand.

### Describe the solution you'd like.

I'd like to create a landing page for the website. It will have some visually appealing components and a CTA button saying "Get Started".

### Describe alternatives you've considered.

A small modal that pops up when the site loads. It will give a small overview of things.

### Add any other context or screenshots about the feature request here.

A reference:

<img width="1440" alt="" src="https://user-images.githubusercontent.com/59930625/157169096-bf824e1b-6ce4-4aac-a77c-96340a52d403.png">

Link: https://www.behance.net/gallery/126616507/Landing-Page

**Comment by Keyurchaniyara** [comment]
Hello @anushkachauhxn 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make website landing page for this issue. Please do assign this to me.

ThankYou:)

**Comment by prachi1211** [comment]
Hello
I am a Gssoc'22 Contributor. Kindly assign me this task.
Thank You.

**Comment by YatreeLadani** [comment]
I'm an GSSOc'22 Contributor, please Assign me this task.

**Comment by praveenscience** [comment]
This task **isn't approved**. It's a good feature, but let's focus on the working app right now. I am not closing this issue because, we might use this later! Thanks.

**Comment by praveenscience** [comment]
Let's move it to the other repo. @anushkachauhxn please ping me for assignment. 😊
