### ISSUE TITLE
Need a semantic accessible tag for navigation elements

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#11]
Currently we have a `<span>` tag. Only the `<a>` tag or `<button>` tag are accessible, not `<span>`. This needs to be checked as well as `<a>` cannot be added directly on React with `href="#"`. This is up for grabs! 😊

**Comment by divyaprakash-Rx** [comment]
@praveenscience I would like to work on this issue. Please assign it to me.

**Comment by praveenscience** [comment]
@divyaprakash-Rx Go for it! 😊

**Comment by divyaprakash-Rx** [comment]
Okay, thanks. I will create PR asap.

**Comment by divyaprakash-Rx** [comment]
@praveenscience I have made span tag accessible and created PR for the same. Please review and merge PR.

**Comment by praveenscience** [comment]
I'll take this over for now and assign you something else. 😊
