### ISSUE TITLE
Feature : Add the user profile picture.

### ISSUE THREAD

**Issue by VanshSh** [CatsInTech/Rezume#111]
### Is your feature request related to a problem? Please describe.

This issue is regarding adding the profile picture in the header section of the page.

### Describe the solution you'd like.

Adding the option to let user add their profile picture on the resume.

### Describe alternatives you've considered.

We can also add the random avatar generator which will add the random avatar pic for the user.

**Comment by praveenscience** [comment]
Please carry on! 😊

**Comment by praveenscience** [comment]
@VanshSh How are you getting on? I am planning to close this as a dupe of #99. Let me know if it's not dupe.
