### ISSUE TITLE
Update the Home Page.

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#122]
### What happened?

Currently the homepage is https://app.rezume.best. It should be https://app.rezyume.co/.

### How can we reproduce this bug?

Check `package.json`.

### Urgency (Optional)

High priority

**Comment by ManjuBhagtani** [comment]
Hi,
I want to work on this issue.

**Comment by praveenscience** [comment]
Wow, it was done so quick! Thanks @ManjuBhagtani! 😊  And here's how we did! 😁

[Video: **Cats in Tech: Rezyume: Issue #122 / PR #123**](https://youtu.be/-2LkLAEap7Y)
