### ISSUE TITLE
Convert the About Us button to a link and update it!

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#124]
### What happened?

We have the About Us button integrated in the app here:

![image](https://user-images.githubusercontent.com/1830380/160605926-c85001cb-9884-4d2c-8489-1e21ee9878fe.png)

At the moment, it's inside a React component as a button. All we need is to convert the button into a `<a>` tag with a link back to https://rezyume.co/.

Simple steps to follow:

- Change `<button>` to `<a>` with classes preserved.
- Add `href` and link it to https://rezyume.co/.
- Make sure to add `target="_blank"`.
- Make sure to add `rel="noopener noreferrer"`.

This is a very simple fix and GSSoC 22 folks, pick it up! 😊 

### How can we reproduce this bug?

We have the About Us button integrated in the app here:

![image](https://user-images.githubusercontent.com/1830380/160605926-c85001cb-9884-4d2c-8489-1e21ee9878fe.png)

If you inspect it and see, it's a button and not a normal link.

### Urgency (Optional)

Medium priority

**Comment by karmankaur09** [comment]
I want to issue

**Comment by karmankaur09** [comment]
I want to work on this issue

**Comment by praveenscience** [comment]
Okay start working on this! 😊
