### ISSUE TITLE
Creating a checklist for the required extensions to be installed on VSCode

### ISSUE THREAD

**Issue by mrunankpawar** [CatsInTech/Rezume#126]
### Is your feature request related to a problem? Please describe.

I was figuring out to install all the required extensions for the project, so just thought that having a checklist in the README itself will be helpful, we already have the extensions mentioned, just need to convert it into the checklist.

### Describe the solution you'd like.

Adding checklist in README.md files, and adding a reference to those extension links.

### Describe alternatives you've considered.

NA

**Comment by praveenscience** [comment]
It's already there in the ReadMe:

![image](https://user-images.githubusercontent.com/1830380/161387516-8150a166-5e8b-4ab5-a013-3fc479c17ee1.png)

What exactly are you trying to do?

**Comment by mrunankpawar** [comment]
I have read the readme, was trying to say that can we add it as a checklist

eg:
- [ ]  Git
- [ ] Node.js

Sorry if it seems to be an invalid issue

**Comment by praveenscience** [comment]
@mrunankpawar makes sense. Wanna pick it up?

**Comment by mrunankpawar** [comment]
Yes, sure
