### ISSUE TITLE
After adding image, name and contact section looks too close

### ISSUE THREAD

**Issue by mrunankpawar** [CatsInTech/Rezume#127]
### What happened?

When we click on the checkbox for **Add Profile Picture** name of the person and their contact details come too close, which looks clumsy. If we reduce the padding on the left and right sides a little, then it looks fine.

### How can we reproduce this bug?

We just need to click on the checkbox next to the Add Profile Picture and you will be able to notice it.
<img width="1440" alt="Screenshot 2022-04-01 at 8 13 10 AM" src="https://user-images.githubusercontent.com/65391854/161184964-7b62f5f5-bc56-4419-a5d3-a067b96c7205.png">

**Comment by praveenscience** [comment]
Seems to be a valid issue! 😢  Wanna pick it up?

**Comment by mrunankpawar** [comment]
Yes, sure

**Comment by Kanika2772002** [comment]
I can fix this issue @mrunankpawar can u assign me??

**Comment by praveenscience** [comment]
@Kanika2772002 It's already been raised and assigned to @mrunankpawar

**Comment by Kanika2772002** [comment]
Ohky ohky

**Comment by praveenscience** [comment]
@mrunankpawar Any updates?

**Comment by mrunankpawar** [comment]
> @mrunankpawar Any updates?

Yep, working on it.
