### ISSUE TITLE
Add the Mini-Leaderboard Link in the ReadMe.

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#138]
### Is your feature request related to a problem? Please describe.

Can we have the [Mini-Leaderboard](https://h0m9hr.csb.app/) link in the ReadMe for a quick access?

### Describe the solution you'd like.

Add the link to the [Mini-Leaderboard](https://h0m9hr.csb.app/) on the ReadMe.

### Describe alternatives you've considered.

None.

**Comment by karmankaur09** [comment]
I want to solve this issue.

**Comment by praveenscience** [comment]
@karmankaur09 Sure, go for it. 😊
