### ISSUE TITLE
Title: Build up the "About Us" page for the app "Rezume"

### ISSUE THREAD

**Issue by zugzwang03** [CatsInTech/Rezume#141]
### Is your feature request related to a problem? Please describe.

On pressing the "About Us" button, the new page opening up contains only one line information about the project. It doesn't necessarily illustrates the main idea and concept behind creating the project.

### Describe the solution you'd like.

I would like to add content about the project in the "About Us" page. Like the basic motto of the project, the kind of solutions it is offering , it is more often like providing a vivid idea about the project.

### Describe alternatives you've considered.

Creating an "About Us" page for the project containing necessary details.

### Add any other context or screenshots about the feature request here.

Also, I want to work on this issue under GSSoC'22.

**Comment by praveenscience** [comment]
Yes, this is a new project altogether and we're waiting for the approval from GSSoC for the same. Kindly check the previous issues for about page please?

**Comment by zugzwang03** [comment]
I want to work on this issue, but the concept of 'new project' is unclear to me. @praveenscience
