### ISSUE TITLE
Title: Making Other Section working To add in Resume

### ISSUE THREAD

**Issue by Abh1shekSingh** [CatsInTech/Rezume#150]
### Is your feature request related to a problem? Please describe.

Yes, I want to add other section of resume to start working. So that user can add projects, experience and other

### Describe the solution you'd like.

I will code Javasript

### Describe alternatives you've considered.

Nothing

**Comment by Abh1shekSingh** [comment]
Please Assign the Task to Me

**Comment by praveenscience** [comment]
Dupe of #73 and #114.
