### ISSUE TITLE
Title: Update Login and SignUp Design

### ISSUE THREAD

**Issue by route-2** [CatsInTech/Rezume#155]
### Is your feature request related to a problem? Please describe.

Design seems very mainstream, would like to make changes to the color scheme and make it more suitable for the site.

### Describe the solution you'd like.

I'd like to alter the color scheme and make the colors more suitable to the website.

### Describe alternatives you've considered.

I would want to add modals instead of a separate page opening while trying to log in and Sign Up.

**Comment by route-2** [comment]
can i work on this issue?

**Comment by praveenscience** [comment]
Not sure how this slipped me... Let's discuss about this soon. 🤘🏻

**Comment by iam-shubham03** [comment]
Please, assigned me I want to work on this problem.

**Comment by praveenscience** [comment]
If anyone wants to start work, lemme know, I can assign and you can start working! 💪🏻
@iam-shubham03 @route-2

**Comment by route-2** [comment]
I would like to work on it!

**Comment by bharat407** [comment]
> If anyone wants to start work, lemme know, I can assign and you can start working! 💪🏻 @iam-shubham03 @route-2

I want to work on it pls assign it.

**Comment by TheXro** [comment]
@route-2 you working on it?

**Comment by praveenscience** [comment]
@route-2 Any updates?

**Comment by naveengitboi** [comment]
Hey @praveenscience  can I work on it?

**Comment by praveenscience** [comment]
Basically the main point of this app is to not login. I don't even understand why we need this.
