### ISSUE TITLE
Implement GitHub Actions for Welcome Messages

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#27]
When a PR or Issue is opened, let's have some GitHub actions do the magic by asking the users to do something or giving some useful information. Currently it's going to be experimental and we need to see the potential of how this can be used, but let's start with something small. 😊

**Comment by Samriddhi25** [comment]
I'll like to take this task

**Comment by mySTRiouscoder** [comment]
I'd like to take this up coz i am working on it already

**Comment by praveenscience** [comment]
@Samriddhi25 Already chosen by @mySTRiouscoder... 😅
