### ISSUE TITLE
Add Pull Request Template and Issue Template

### ISSUE THREAD

**Issue by Aman-Codes** [CatsInTech/Rezume#29]
@praveenscience  I am a GSSOC participant and I would like to add a  pull request template and an issue template folder with bug report and feature request template.
### Pull Request
![pull request](https://user-images.githubusercontent.com/54680709/77220497-9c386800-6b66-11ea-9d0a-72820d72a239.PNG)

### Bug report
![bug report](https://user-images.githubusercontent.com/54680709/77220483-80cd5d00-6b66-11ea-8685-2751fa20c0c2.PNG)

### Feature Request
![feature request](https://user-images.githubusercontent.com/54680709/77220495-98a4e100-6b66-11ea-8197-e72016d126c0.PNG)

**Comment by praveenscience** [comment]
@Aman-Codes Go for it! 😊
