### ISSUE TITLE
Add CI / CD + Netlify Support

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#3]
Currently we are using GitHub Pages and creating a build, pushing it to `gh-pages` branch and updating the build files by the following process in command line using :

- Delete the build folder.
- Recreate the build folder.
- Create a `CNAME` file.
- Using `gh-pages` package, deploy the contents of build to `gh-pages` branch.

The above process needs to be automated using Continuous Integration / Continuous Deployment Pipelines using either Travis-CI or GitHub Actions. Once the build is done, this needs to be deployed automatically, if everything is successful to `app.rezume.best` through Netlify. This is up for grabs! 😊

**Comment by abhu-A-J** [comment]
@praveenscience May I try this! Never done this before so would like to give it a shot

**Comment by praveenscience** [comment]
@abhu-A-J Are you sure? Coz this is gonna hit the production and I want this to be perfect. Possible man? (Just worried what if this involves some £₹$ money and we shouldn't screw it up)...

**Comment by abhu-A-J** [comment]
> @abhu-A-J Are you sure? Coz this is gonna hit the production and I want this to be perfect. Possible man? (Just worried what if this involves some £₹$ money and we shouldn't screw it up)...

I'll do my best to do this. I think I'll be able to do with proper research and study. Im up for it

**Comment by praveenscience** [comment]
Go for it! @abhu-A-J 😊

**Comment by mySTRiouscoder** [comment]
I'll add appropriate github actions as well.

**Comment by praveenscience** [comment]
Yep, let's both discuss this one. 😊
