### ISSUE TITLE
Use the defaultValue or value props instead of setting children on textarea.

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#33]
There seems to be some input `defaultValue` issue with the connected components.

**To Reproduce**
1. Go to https://rezume.best/
2. Open the F12 DevTools and click Console.
3. You can find the error on console.

**Expected behavior**
The `<textarea>` needs to have a `defaultValue`.

**Screenshots**

![image](https://user-images.githubusercontent.com/1830380/77855674-db5f5c80-71e9-11ea-959e-c480ef6041b3.png)

**Comment by praveenscience** [comment]
Go for it! @shreyakapoor08 😊

**Comment by shreyakapoor08** [comment]
> Go for it! @shreyakapoor08 😊

PR raised :)
