### ISSUE TITLE
Add a version for the deployment in the footer

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#4]
The version could be the commit ID of the current build on the master branch. Somehow we need to fetch the version information using the commit hash and that needs to be shown either using:

- a text on footer of the application
- a variable on the page
- a comment inside the source

I have seen a few people doing it, which I need to check with them. But this is again up for grabs. 😊 Best idea would get some nice chocolates! 🍫

**Comment by habeeba-naaz** [comment]
I am interested to work...please assign

**Comment by praveenscience** [comment]
@habeeba-naaz Done... 😊

**Comment by habeeba-naaz** [comment]
Thank you @praveenscience

**Comment by habeeba-naaz** [comment]
Publishing git commit Info publicly is not a good idea. So I prefer to do a comment inside the source.

**Comment by praveenscience** [comment]
Git commit hashes are public. The repository is open source. We need it. 😊 The main thing is it needs to be public so that we can debug things easily.

**Comment by habeeba-naaz** [comment]
Oh...then shall I do as a variable on the page?This should be done in JavaScript code?

**Comment by praveenscience** [comment]
Yep that works! 😊

**Comment by habeeba-naaz** [comment]
Do I need to do this task in master branch without checkout to new branch?

**Comment by praveenscience** [comment]
@habeeba-naaz I am writing the contribution guidelines in few mins. Will send it to you! 😊

**Comment by habeeba-naaz** [comment]
Actually I should not do in master branch...but in issue it’s mentioned to get version of current build of master branch..so got confused..

**Comment by praveenscience** [comment]
The SHA won't change irrespective of `master` branch or `feature` branch. 😊

**Comment by habeeba-naaz** [comment]
Oh..I got it..thank you for your patience for answering my questions

**Comment by aldrinjenson** [comment]
@habeeba-naaz  are you still working on this?

**Comment by habeeba-naaz** [comment]
Yes

**Comment by habeeba-naaz** [comment]
![Rezume-error](https://user-images.githubusercontent.com/29932609/78412351-04646080-75e1-11ea-9b76-2b4b7db86133.png)

**Comment by habeeba-naaz** [comment]
I made PR ...it has to be reviewed

**Comment by praveenscience** [comment]
@Hyraze Sorry, didn't get you. What's the use of using it on `package.json`?
@habeeba-naaz I'll check it out, thanks.

**Comment by Gurdeep475** [comment]
Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by praveenscience** [comment]
@Gurdeep475 Go ahead, let's check the progress in 2 days! 🎉

**Comment by praveenscience** [comment]
Check these for more info:

- [`react-git-info` - npm](https://www.npmjs.com/package/react-git-info)
- [Add git information to create-react-app](https://stackoverflow.com/questions/48391897/add-git-information-to-create-react-app)

**Comment by Gurdeep475** [comment]
Thanks for the resources. I am working on it.

**Comment by Gurdeep475** [comment]
@praveenscience I am getting this error, when I do: npm start
![image](https://user-images.githubusercontent.com/32095032/156558191-9d36e6a3-8e4e-45d1-8a97-8e0d88ade6bf.png)

Things I have tried:
1. deleting node-sass and installing saas

not able to solve the error please guide me.

**Comment by praveenscience** [comment]
Okay, everyone seems to get this issue.

Some 🤬 messed it up. Can you please downgrade to `4.11.0` using `npm i node-sass@4.11.0` please?

**Comment by Gurdeep475** [comment]
> Can you please downgrade to `4.11.0` using `npm i node-sass@4.11.0` please?

I tried it but still got errors
![image](https://user-images.githubusercontent.com/32095032/156561791-716144c2-f6ae-4a00-939a-745e9d9bca8a.png)

**Comment by praveenscience** [comment]
Try the version 5?

**Comment by Gurdeep475** [comment]
nope, any other work-around, tried all versions from 7 to 3 but nothing works.

**Comment by praveenscience** [comment]
@Gurdeep475 Many of them said 4 or 5 works. Hey, did you downgrade your Node JS version? Okay, let me do one thing. I'll add another issue to upgrade the app for working with Node 16.

**Comment by Gurdeep475** [comment]
@praveenscience my PR was not recognized in GSSOC because there are no lables given to this issue. Please attach the relevant labels.

**Comment by praveenscience** [comment]
@Gurdeep475 Definitely this has labels:

![image](https://user-images.githubusercontent.com/1830380/161387755-e429ae0f-27a6-4918-a346-e56ba6232466.png)

Labels are for PRs not issues.

**Comment by praveenscience** [comment]
I don't understand. It's even there right in front on [the trailer](https://rb.gy/gitxip) too! What happened?

![image](https://user-images.githubusercontent.com/1830380/161387872-426e85c4-14a0-4888-8b74-a13e0c382181.png)

Let me know where the problem is? Show this to Monish then...
