### ISSUE TITLE
Add a section for Work Samples

### ISSUE THREAD

**Issue by csharp489** [CatsInTech/Rezume#43]
We should have one more section for **Work Samples**. It consists of 4 elements.
1 Blog Link
2 GitHub Profile
3 Play Store Developer A/c (Public Link)
4 Behance Portfolio Link
5 Other Portfolio Link

This section is important for experience as well as for fresher.
@praveenscience please review it.

**Comment by praveenscience** [comment]
Hi @csharp489 That's exactly #15 does, right? This is a duplicate of #15.

**Comment by aryamasinha** [comment]
@praveenscience @csharp489  can i take up this issue?

**Comment by rithika-hebbar** [comment]
@praveenscience I would like to work on this issue.

**Comment by arpitasahakundu** [comment]
i would like to work on this

**Comment by praveenscience** [comment]
Sorry all, this is a dupe of #15. 😔
