### ISSUE TITLE
Add TOC to README.md

### ISSUE THREAD

**Issue by jamesjose03** [CatsInTech/Rezume#44]
**Is your feature request related to a problem? Please describe.**
Currently, the readme is quite a long one. 

**Describe the solution you'd like**
A TOC will help for easy navigation through the README file.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot
![image](https://user-images.githubusercontent.com/31133182/78252450-7de04e00-7510-11ea-81da-130f626ce64d.png)

**Comment by jamesjose03** [comment]
I am a GSSOC participant. Pls assign me this issue. I would like to work on it

**Comment by praveenscience** [comment]
@jamesjose03 Go for it. 😊

**Comment by jamesjose03** [comment]
Okay, thanks. 👍

**Comment by praveenscience** [comment]
Actually I had this as a part of #1. @AnjaliSharma1234 did you miss this? 😅

**Comment by AnjaliSharma1234** [comment]
I think it's a nice idea! @jamesjose03 @praveenscience
