### ISSUE TITLE
Add Link to the brand name in header.

### ISSUE THREAD

**Issue by imabp** [CatsInTech/Rezume#46]
**No hyperlink in the brand name in header REZUME**

**To Reproduce**
1. Go to 'localhost:3000'
2. Click on 'the brand name REZUME, you will not be redirected to home page.'

**Expected behavior**
On clicking brandname that is Rezume, should redirect us to the homepage. .

**Screenshots**

![image](https://user-images.githubusercontent.com/53480076/78340361-9b1a2880-75b3-11ea-8aed-efe7f628acb2.png)

**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [80.0.3987.149]

**Comment by praveenscience** [comment]
Hey, but we don't have a home page yet right? Like where exactly it needs to take us? It's just a Single Page App right?

**Comment by imabp** [comment]
It should take us to '/' page sir

**Comment by scortier** [comment]
@praveenscience Can you please assign me this task.

**Comment by imabp** [comment]
@scortier  Its not required. @praveenscience  sorry to reply so late because i was on a project with a healthcare department. Yaa, Actually  I got the issue ....its fine.. sorry for showing hurry at that  time
