### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by aldrinjenson** [CatsInTech/Rezume#48]
I think it would be nice to add a simple Footer to the app.

The left side can be used to show the version of the app like in #4
and the centre part can be used to show a copyright link like a 
copyright 2020 Rezume
etc.
Note: The footer will be seen only if the we scroll down to the bottom and that way the user will not be limited by the space available for the Resume created.

**Comment by aldrinjenson** [comment]
@praveenscience I am interested in working this out

**Comment by spacemonkey1101** [comment]
is this still open?

**Comment by silenteyesoncode** [comment]
I want to contribute into this project,
