### ISSUE TITLE
Add Code_of_Conduct.md file and link it to readme.md file

### ISSUE THREAD

**Issue by csharp489** [CatsInTech/Rezume#56]
No Code of Conduct file is present.
As a gssoc Participant, I would like to add Code_of_Conduct.md file and link it to the readme.md file.
@praveenscience @AnjaliSharma1234 please assign me this task.

**Comment by praveenscience** [comment]
@csharp489 It's already there in [`Rezume/CONTRIBUTING.md`](https://github.com/CatsInTech/Rezume/blob/master/CONTRIBUTING.md).

![image](https://user-images.githubusercontent.com/1830380/79548860-0113af00-808e-11ea-974b-48ac449b108f.png)
