### ISSUE TITLE
Shall we discuss a neat logo?

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#6]
Yet another discussion based issue. I am also looking for an awwwesome logo for this. I really love how flat logos exist. Let's stick with the four designs ranging from most preferred to least preferred:

- [Lineal Colour](https://image.flaticon.com/icons/svg/2729/2729001.svg) (most preferred)
- [2 Colours](https://image.flaticon.com/icons/svg/2718/2718609.svg)
- [Colour](https://image.flaticon.com/icons/svg/2731/2731280.svg)
- [Lineal](https://image.flaticon.com/icons/svg/2728/2728983.svg) (least preferred)

Let's have the theme in a studenty way! This one's up for grabs and best design is gonna get 7 points. 😊

**Comment by priyadarshu** [comment]
Can you please assign me this. Would like to know more about it

**Comment by praveenscience** [comment]
@priyadarshu go for it... Let's discuss it and we'll finalise... 😊 Go for it and post your designs... It would be nice to show some ideas and then if we select one, we'll assign the PR.

**Comment by anushreejain98** [comment]
Should we make a design using paper pen or some logo design tool like Adobe XD?

**Comment by praveenscience** [comment]
@anushreejain98 Anything is okay, but the final output needs to be one of the above mentioned:

> - [Lineal Colour](https://image.flaticon.com/icons/svg/2729/2729001.svg) (most preferred)
> - [2 Colours](https://image.flaticon.com/icons/svg/2718/2718609.svg)
> - [Colour](https://image.flaticon.com/icons/svg/2731/2731280.svg)
> - [Lineal](https://image.flaticon.com/icons/svg/2728/2728983.svg) (least preferred)

**Comment by anushreejain98** [comment]
![Screenshot from 2020-03-26 23-03-04](https://user-images.githubusercontent.com/30777215/77677676-082b2e00-6fb6-11ea-8f74-65ad38cf7f48.png)
![Screenshot from 2020-03-26 23-03-10](https://user-images.githubusercontent.com/30777215/77677692-0cefe200-6fb6-11ea-888b-3200e18f9d6e.png)
![Screenshot from 2020-03-26 22-59-51](https://user-images.githubusercontent.com/30777215/77677708-12e5c300-6fb6-11ea-8a2a-271a3741445c.png)
![Screenshot from 2020-03-26 23-00-03](https://user-images.githubusercontent.com/30777215/77677716-15e0b380-6fb6-11ea-96dc-55495a3167f0.png)
![Screenshot from 2020-03-26 23-00-31](https://user-images.githubusercontent.com/30777215/77677731-1a0cd100-6fb6-11ea-9434-e0a78d8b5c10.png)
![Screenshot from 2020-03-26 22-59-02](https://user-images.githubusercontent.com/30777215/77677737-1d07c180-6fb6-11ea-93c2-15b576462fff.png)

**Comment by anushreejain98** [comment]
I tried some of these, Is any of the above logos created eye-catchy? should we come up with slogan as well? @praveenscience

**Comment by praveenscience** [comment]
Wow, really good... I really like the below one:

![image](https://user-images.githubusercontent.com/1830380/77678666-655cba80-6f89-11ea-96fe-fa23e13823bc.png)

**Comment by anushreejain98** [comment]
@praveenscience thank you, do we need to modify this or make further improvisation, think of slogan as well?

**Comment by praveenscience** [comment]
@anushreejain98 Can you get the logotype to be in two lines with a sentence case? I guess this is good to go for me now.

**Comment by anushreejain98** [comment]
> @anushreejain98 Can you get the logotype to be in two lines with a sentence case? I guess this is good to go for me now.
@praveenscience sure, you mean, the logo should fit in 2 lines?
 Also I am planning to replace Resume Generator with Rezume? will that be fine?

**Comment by aldrinjenson** [comment]
Hi, @anushreejain98 , appreciate your efforts in seeking out a logo, but I think usually in professional organizations, they want the logo to be as simple as possible. i.e, if there is usually a lot of colours and trendy designs, there are chances for companies to consider us as amateurish maybe. So I personally feel that it would be best to make a simple logo without much eye catchy effects or bright colours. I generated these two logos using an online logo designer tool. Please see if you agree.
![free_horizontal_on_white](https://user-images.githubusercontent.com/53407417/78370611-7ee2af80-75e4-11ea-8a92-2af96e8894d8.png)
![free_horizontal_on_white_green](https://user-images.githubusercontent.com/53407417/78370615-8013dc80-75e4-11ea-944a-039968504047.png)

**Comment by Kashish-max** [comment]
@aldrinjenson I think the logo should convey the purpose of our product with minimalism. I also made a logo. @parveenscience please checkout this - -

![Rezume-logo-4](https://user-images.githubusercontent.com/53968505/78541824-df0b6880-7813-11ea-9c99-b27764ff3583.png)

**Comment by annu12340** [comment]
Is this issue still open?
I would like to work on it

**Comment by praveenscience** [comment]
I was waiting for @anushreejain98's update on SVG logo and changes with #41. So yea, until it's finalised keep trying.

**Comment by annu12340** [comment]
Hey everyone, I have some ideas for the logo
![logo1](https://user-images.githubusercontent.com/43414928/78580380-f36d5680-784f-11ea-8cb2-de39cdc4b90a.png)
![l2](https://user-images.githubusercontent.com/43414928/78580386-f5371a00-784f-11ea-936f-1655a3f61cdb.png)
![l3](https://user-images.githubusercontent.com/43414928/78580390-f6684700-784f-11ea-9b09-1ab6fd063673.png)
![l4](https://user-images.githubusercontent.com/43414928/78580397-f700dd80-784f-11ea-936e-0cb14f9c64a9.png)
![l6](https://user-images.githubusercontent.com/43414928/78580399-f7997400-784f-11ea-85f8-607ac24004c3.png)
![l7](https://user-images.githubusercontent.com/43414928/78580400-f8320a80-784f-11ea-909d-3628826b3c8a.png)
![l8](https://user-images.githubusercontent.com/43414928/78580402-f8caa100-784f-11ea-9a25-b76590d4f081.png)

**Comment by SomyaGandhi** [comment]
![Black and Red Laser Games Logo (4)](https://user-images.githubusercontent.com/53896115/78809776-0bc2aa00-79e5-11ea-8fc5-373fa58d5cf1.png)

**Comment by SomyaGandhi** [comment]
![Black and Red Laser Games Logo (1)](https://user-images.githubusercontent.com/53896115/78810490-0dd93880-79e6-11ea-8b51-a2e2e31e827e.png)
![Black and Red Laser Games Logo (3)](https://user-images.githubusercontent.com/53896115/78810500-129dec80-79e6-11ea-8025-df383229484b.png)
![Black and Red Laser Games Logo (5)](https://user-images.githubusercontent.com/53896115/78810518-1762a080-79e6-11ea-92ed-9c6ada3805a4.png)
![Black and Red Laser Games Logo (6)](https://user-images.githubusercontent.com/53896115/78810542-1df11800-79e6-11ea-8220-e1ff522f60dc.png)
![Black and Red Laser Games Logo (2)](https://user-images.githubusercontent.com/53896115/78810575-25182600-79e6-11ea-974f-d1ebfc3519a0.png)

**Comment by praveenscience** [comment]
@BabyElias Please comment here, I'll assign this to you.

**Comment by BabyElias** [comment]
Assign me this issue.

**Comment by praveenscience** [comment]
@BabyElias Please start working on a better logo! 😊

**Comment by BabyElias** [comment]
Sure Sir !

**Comment by BabyElias** [comment]
The links provided in the issue are broken.Do I need to refer any of those?

**Comment by praveenscience** [comment]
Yea, sorry about that, it's been 2 years and the sites are down. This is lineal colour logo:

![image](https://user-images.githubusercontent.com/1830380/158367106-b083397c-73f9-4f4f-b665-663d56d4fd6d.png)

These are two colour logos:

![image](https://user-images.githubusercontent.com/1830380/158367150-4f9bd9e9-9407-4155-a330-7845bbdf1471.png)

Find something like this, thanks.

**Comment by BabyElias** [comment]
ohkay Sir

**Comment by Abhilasha-Jairath** [comment]
Hello sir !!

**Comment by praveenscience** [comment]
@Abhilasha-Jairath meet @BabyElias and she's got an awesome cool stuff too. Please discuss together and come up with something super cool.

**Comment by Abhilasha-Jairath** [comment]
Sure sir!!

**Comment by praveenscience** [comment]
@BabyElias Add me too! 😊  canva@praveen.science

**Comment by BabyElias** [comment]
Ok Sir ! I sent a request to your email ID canva@praveen.science .

**Comment by Abhilasha-Jairath** [comment]
> Hello @Abhilasha-Jairath .I have just started designing on Canva pro.If you want, you can give me your email id and I shall add you as a teammate on Canva pro & we can work on it together! Message me on Discord.Your discord id please?

Im unable to join @BabyElias

**Comment by BabyElias** [comment]
@Abhilasha-Jairath Did you receive the invite link on your mail?

**Comment by Abhilasha-Jairath** [comment]
> @Abhilasha-Jairath Did you receive the invite link on your mail?

ya i did !! but unable to join

**Comment by Abhilasha-Jairath** [comment]
Ok im in !! i somehow joined canva withyour link @BabyElias 
Whats the next task? @praveenscience

**Comment by praveenscience** [comment]
I am still waiting for it! 😅

**Comment by Abhilasha-Jairath** [comment]
> Are we still working on it @Abhilasha-Jairath @praveenscience ?

Yes I did received the link and joined it. 
Yes !!

**Comment by praveenscience** [comment]
@BabyElias Wanna post the screenshots here? 😊

**Comment by BabyElias** [comment]
![REZUME (3)](https://user-images.githubusercontent.com/95405559/162554403-f6cb7800-5078-4fff-9e6c-91dddf6a9c3c.png)
![REZUME (2)](https://user-images.githubusercontent.com/95405559/162554406-e9ed4209-c19e-4186-b424-519480d3a979.png)
![REZUME (1)](https://user-images.githubusercontent.com/95405559/162554407-64fcb6e3-2442-4a7e-8a76-d1e5ce3e8abc.png)

**Comment by praveenscience** [comment]
I love the second one:

![image](https://user-images.githubusercontent.com/1830380/162609501-faadce2c-94d5-475d-816c-b3859536a233.png)

**Comment by BabyElias** [comment]
Great! Any more changes you would like to suggest? Or should I generate a PR for the same?

**Comment by praveenscience** [comment]
Nopes... Need these as a part of PR:

- FavIcon Update
- OG Image Update

Think of a better way of adding it to the Nav... 😊

**Comment by BabyElias** [comment]
Ok Sure.Will try to incorporate it that way in a day or two and discuss with you.😊

**Comment by praveenscience** [comment]
Excellent, thanks @BabyElias. Looking forward.

**Comment by BabyElias** [comment]
https://drive.google.com/file/d/1_TOIHBzY3Bozjv43YBz20LLzhEFDw54n/view?usp=sharing

This is the favicon part of it. Image breaks on extensive zooming(because had to maintain the size of 48*48px) but at a 100% range works well.Check it out once @praveenscience

**Comment by BabyElias** [comment]
These are the ideas for OG Image.Let me know which one appeals the most!

![REZUME (13)](https://user-images.githubusercontent.com/95405559/162670033-68ddfff6-cea6-40e7-906b-830ecf644fe1.png)
![REZUME (12)](https://user-images.githubusercontent.com/95405559/162670059-c21d3922-5b78-4f56-b7d1-2e158a06b312.png)
![REZUME (11)](https://user-images.githubusercontent.com/95405559/162670076-5b11865a-556a-4eed-8474-340cd16af2c5.png)
![REZUME (10)](https://user-images.githubusercontent.com/95405559/162670083-13b0e280-d3dc-462b-839d-10ac63a2343c.png)
![REZUME (9)](https://user-images.githubusercontent.com/95405559/162670086-02a58a22-333d-4c34-bb9f-48789c260a75.png)
![REZUME (6)](https://user-images.githubusercontent.com/95405559/162670087-3b9fd3c1-39a5-4e09-a346-05928de87e4c.png)
![REZUME (8)](https://user-images.githubusercontent.com/95405559/162670089-cb875df0-970c-4c4e-ae69-bf8ab16f55b0.png)

**Comment by praveenscience** [comment]
Last plain one for OG Image, thanks.

**Comment by BabyElias** [comment]
So, the icon and OG images are approved. About adding it to navbar, do I have to add it and then generate the PR with those changes or just suggest some changes? Maybe @Abhilasha-Jairath can help with this part.

**Comment by praveenscience** [comment]
Yes please, @BabyElias

**Comment by ikavyajain** [comment]
Hello Sir, I have another sample of a logo. Can I work on it?
Here's the sample to it! 
![image](https://user-images.githubusercontent.com/89743157/162975281-daf086fe-0bad-4adc-b365-342931cd6d3a.png)

**Comment by Abhilasha-Jairath** [comment]
> So, the icon and OG images are approved. About adding it to navbar, do I have to add it and then generate the PR with those changes or just suggest some changes? Maybe @Abhilasha-Jairath can help with this part.

No changes required !! Everything seems to be perfect .
