### ISSUE TITLE
:feat: email section at the left sideBar

### ISSUE THREAD

**Issue by aashimgarg** [CatsInTech/Rezume#61]
**Is your feature request related to a problem? Please describe.**
Yes the left sideBar does not contain the e-mail section  for which user can add their email to the the rezume.

**Describe the solution you'd like**
I would like to add the email email section to the left sideBar.

@praveenscience what are your thoughts.? We can include even the Website and Phone number section too.

**Comment by praveenscience** [comment]
You get this in the Contact Section right?

![image](https://user-images.githubusercontent.com/1830380/81729800-7bb0ce00-9484-11ea-8321-e50239fdca9f.png)

**Comment by aashimgarg** [comment]
Ok! I got that.
