### ISSUE TITLE
On writing something the form fields are getting disappeared

### ISSUE THREAD

**Issue by Utkarsh2801** [CatsInTech/Rezume#63]
**Expected behavior**
On writing something in form fields resume should be updated

**Comment by Utkarsh2801** [comment]
I forked and tried to run the app on my localhost But I found some unexpected behavior of form fields. Form fields are getting disappeared whenever I'm trying to give some input. I want to work on this issue please assign it to me.

**Comment by rohanJa** [comment]
@Utkarsh2801 I resolved it in #62 you can look in that

**Comment by Utkarsh2801** [comment]
Ohhh, Okay the pull request hasn't been merged yet
