### ISSUE TITLE
Add email, phone and website editing fields

### ISSUE THREAD

**Issue by Siddhesh777** [CatsInTech/Rezume#79]
**Is your feature request related to a problem? Please describe.**
We have to add our own email, phone and website in resume but there is no field to make changes in email, phone and website.

![Issue](https://user-images.githubusercontent.com/77476772/156300983-57d5d45c-7f23-4a30-aee8-ac695562d801.png)

**Describe the solution you'd like**
I will add a field to get the phone, email and website details from the user and will display the changes in resume

**Additional context**
I am student of VNIT Nagpur,CSE 2nd year.
I am contributor at GSSoC '22. Please assign this issue to me.

**Comment by praveenscience** [comment]
It's already there. Can you explain what you're trying to do and I'll reopen this again?
