### ISSUE TITLE
Add text field to input Projects, Skills, Hobbies section

### ISSUE THREAD

**Issue by Pranai2518** [CatsInTech/Rezume#80]
**Is your feature request related to a problem? Please describe.**
There is no text field to add the projects, skills and hobbies.

**Describe the solution you'd like**
 I would like to add the text field for the projects, skills and hobbies. 

**Additional context**
![image](https://user-images.githubusercontent.com/75829770/156363084-b4342498-4c27-448d-a176-1c6b0c9dbfa0.png)

I am a GSSOC'22 participant.

**Comment by praveenscience** [comment]
Dupe of #73!

**Comment by goyalsaksh** [comment]
Hello, I am A gssoc contributor and a beginner.please assign this issue to me.

**Comment by praveenscience** [comment]
> Hello, I am A gssoc contributor and a beginner.please assign this issue to me.

@goyalsaksh Please don't get any more strikes / penalties, kindly read the above message! Just think what employers and others might think looking at this?

Had I been looking for a Front End engineer to join my team, I'll reject the application because of this:

**Comment by praveenscience** [comment]
@Pranai2518 What's the status?

**Comment by Pranai2518** [comment]
Hey, @praveenscience I have exams till this Tuesday. I will try to complete the issue this week.

**Comment by praveenscience** [comment]
@Pranai2518 What happened?

**Comment by Pranai2518** [comment]
@praveenscience it is done by someone PR #114

**Comment by praveenscience** [comment]
Ah alright! 👍
