### ISSUE TITLE
Changing Occupation Position and separate it from Summary

### ISSUE THREAD

**Issue by Harshil-Jani** [CatsInTech/Rezume#81]
**Describe the bug**
The Occupation of the person appears right next to the description about the person. But, It should be somewhere just next to Name of the person. 
**To Reproduce**

**Expected behavior**
We must expect the profession being in a separate line and detached from the Paragraph.

**Screenshots**
![image](https://user-images.githubusercontent.com/79367883/156389766-93f6a3e6-0a0a-40cf-9e60-78ecece78fcd.png)

**Additional context**
I would like to solve this under GSSOC 2022 Program.

**Comment by praveenscience** [comment]
This is the expected output from the original represent.io! 😁
