### ISSUE TITLE
Make Copyright Year Dynamic

### ISSUE THREAD

**Issue by Harshil-Jani** [CatsInTech/Rezume#82]
**Describe the bug**
The copyright in the Footer has a hardcoded string for year 2020. We can make this Dynamic and then it will get updated automatically as the year will be changing.

**Expected behavior**
Change the Year in the footer from copyright as it changes and remove hardcoded value.

**Screenshots**
![image](https://user-images.githubusercontent.com/79367883/156401554-d08abd9e-e132-47f7-aa48-ac7fd0016146.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser : Chrome
 - Version : 98

**Additional context**
I would like to work for this under GSSOC 2022 Program
- I will be combining #81 and this issue under one PR.

**Comment by MitAbhay** [comment]
Assign this to me.

**Comment by praveenscience** [comment]
@MitAbhay if you're asking for assignment blindly, it won't happen. This issue seems to be fixed already. Kindly have some concern.

**Comment by praveenscience** [comment]
@MitAbhay if you're asking for assignment blindly, it won't happen. This issue seems to be fixed already. Kindly have some concern.
