### ISSUE TITLE
Make app workable for Node 16 and latest node-sass.

### ISSUE THREAD

**Issue by praveenscience** [CatsInTech/Rezume#91]
### What happened?

Seems like there are so many issues when developers are running the app with newer Node & `node-sass` versions.

### How can we reproduce this bug?

Using a new Node installation with latest `node-sass` version breaks the app.

### Urgency (Optional)

High priority

**Comment by bhuvan2002** [comment]
Hello, Please assign it to me as I am GSSOC contributor

**Comment by the-halfbloodprince** [comment]
I'm a GSSoC 2022 contributor and I came across this error in another one of my earlier projects and it has been fixed completely, so I would like you to assign this to me please.
