### ISSUE TITLE
It's GSSoC 2022 not 2020

### ISSUE THREAD

**Issue by setco-website** [CatsInTech/Rezume#95]
### What happened?

In the ReadMe, you have mentioned that it's GSSoC 2020 but we're in 2022.

Dude, are you stuck in a time warp or something?

### How can we reproduce this bug?

See the readme.

### Urgency (Optional)

High priority

**Comment by setco-website** [comment]
I would like to pick up this issue, please assign this to me.

**Comment by praveenscience** [comment]
@setco-website Yes, you're right, please go ahead and start working.
