### ISSUE TITLE
Add social media icons instead of their name 

### ISSUE THREAD

**Issue by suman-shah** [CatsInTech/Rezume#98]
### Is your feature request related to a problem? Please describe.

adding some beautiful icons or symbols against the name of social media handles give it a great look

### Describe the solution you'd like.

i would like to add some social media handles icons to resume page also web icons instead of website text

### Describe alternatives you've considered.

i would probably go with modern design

**Comment by suman-shah** [comment]
can you please assign this issue to me

**Comment by tyagipriyanshi79** [comment]
Hey!! can you assign it to me for GSSOC'22 tag . I'll able to do it with the help of material-ui using reactjs and I'll able to write a clean and understandable code !!

**Comment by praveenscience** [comment]
Wait, what's this about @suman-shah? Can you explain more?

**Comment by praveenscience** [comment]
No response, so closing...
