### ISSUE TITLE
Title: Allow users to add their image in the resume.

### ISSUE THREAD

**Issue by sebinfrancis7** [CatsInTech/Rezume#99]
### Is your feature request related to a problem? Please describe.

Many of the resume generating website allow users to add their profile image in the resume. I think this feature would enhance the project.

### Describe the solution you'd like.

Create an "add image" button which can be used to add an image in the resume. The users would have a choice whether they would like to add an image or not.

### Describe alternatives you've considered.

.

**Comment by sebinfrancis7** [comment]
I would like to work on this issue as part of GSSoC 2022.

**Comment by arinasiddiqui786** [comment]
I have learnt HTML,CSS,JS and react JS and would like to work on this issue .please assign me this project ans I would love to work under GSSOC'22.

**Comment by sebinfrancis7** [comment]
@praveenscience can you please check this issue.

**Comment by praveenscience** [comment]
@sebinfrancis7 Please carry on... For some reason GitHub didn't show me that you created this! 😓

**Comment by praveenscience** [comment]
Also, someone tried to start working on the same issue as a part of #111. But has been closed to get this one up.

**Comment by VanshSh** [comment]
> Also, someone tried to start working on the same issue as a part of #111. But has been closed to get this one up.

Thanks for closing my issue. 
When I was going through all the issue I didn't saw that same issue has been created.

Thankfully we saved time.
I will look for another feature to add

**Comment by praveenscience** [comment]
@VanshSh I hope you haven't started anything. Have you started, please collab with the other person. No problem if you both are working together and adding value man!!!

**Comment by sebinfrancis7** [comment]
Thank you @praveenscience 
@VanshSh if you have started working on this issue or if you have any inputs, would love to work together.

**Comment by VanshSh** [comment]
> @VanshSh I hope you haven't started anything. Have you started, please collab with the other person. No problem if you both are working together and adding value man!!!

I just prepared the rough layout about the issue.

Yeah sure I would try to contact the issue #99 owner and see if we both can contribute to it.

**Comment by praveenscience** [comment]
@sebinfrancis7 and @VanshSh Please team up and do a great job. Will be more than happy to treat you both with goodies! 🎉

**Comment by VanshSh** [comment]
> Thank you @praveenscience @VanshSh if you have started working on this issue or if you have any inputs, would love to work together.

Yeah that would be great idea. ✌️.
Will share some ideas with you tomorrow.

**Comment by VanshSh** [comment]
> @sebinfrancis7 and @VanshSh Please team up and do a great job. Will be more than happy to treat you both with goodies! 🎉

Thanks @praveenscience . 
We will do our best.

**Comment by sebinfrancis7** [comment]
@VanshSh You can connect with me on Linkedin. 
This is my profile https://www.linkedin.com/in/sebinfrancis.

**Comment by VanshSh** [comment]
> @VanshSh You can connect with me on Linkedin. This is my profile https://www.linkedin.com/in/sebinfrancis.

DMed you
